# Setup
title:               IDEEAS Lab
tagline:             'IDEEAS Lab tagline'
description:         'IDEEAS Lab description'
url:                 http://ideeaslab.github.io
baseurl:             http://ideeaslab.github.io/ideeaslab.github.io/
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Andrew Katz
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             Lanyon
google_analytics_id: #UA-XXXX-Y
