# Setup
title:               IDEEAS Title gh
tagline:             'IDEEAS Tagline gh'
description:         'IDEEAS Description gh'
url:                 http://ideeaslab.github.io
baseurl:             http://ideeaslab.github.io/ideeaslab.github.io/
gems:                [jekyll-paginate, jekyll-gist]
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              AK
  url:               https://twitter.com/doc_katz
  email:             markdotto@gmail.com

# Gems
#plugins:
#  - jekyll-paginate

# Custom vars
version:             Lanyon
#version:             1.1.0
google_analytics_id: #UA-XXXX-Y
